let data2 = [
  {
    id: 8,
    title: "고구마반생크림반케이크",
    content: "달콤한 고구마케이크와 상큼한 딸기생크림케이크가 어우러진 반반케이크",
    price: "46,000원",
    sort:"cake",
    image: "/halfhalfcake.png",
    resource:"빵류[군고구마페이스트/인도네시아산,식물성크림(팜핵부분경화유/인도네시아산,정제소금/미국산),호박고구마다이스(호박고구마/국산)],샤인머스캣/국산",
    kcal: 220,
    sodium: 80,
    sugars: 10,
    fat: 6,
    protein: 3,
  },
  {
    id: 9,
    title: "뉴욕치즈케이크",
    content: "크림치즈 본연의 맛을 더해 부드럽고 촉촉한 치즈케이크",
    price: "37,000원",
    sort:"cake",
    image: "/cheesecake.png",
    resource:"자연치즈1/미국산(우유,크림,정제소금,로커스트콩검,치즈컬쳐),자연치즈2/호주산(우유,크림,정제소금,스테빌라이저,스타터컬쳐),설탕,빵류[설탕,밀가루(밀/미국산),난백액(계란/국산)",
    kcal: 325,
    sodium: 190,
    sugars: 25,
    fat: 12,
    protein: 7,
  },
  {
    id: 10,
    title: "블레싱 레드베리",
    content: "축복이라는 꽃말의 포인세티아를 모티브한 고급디자인",
    price: "39,000원",
    sort:"cake",
    image: "/redcake.png",
    resource:"빵류[빵류{전란액(계란/국산)},가공유크림/프랑스산, 냉동딸기①/칠레산, 냉동딸기②/폴란드산],딸기/국산",
    kcal: 195,
    sodium: 65,
    sugars: 12,
    fat: 4.3,
    protein: 3,
  },
  {
    id: 11,
    title: "치킨커틀릿샐러드랩",
    content: "다이어터를 위한 든든하고 건강한 한 끼로 강력추천!",
    price: "6,100원",
    sort:"salad",
    image: "/chickensalad.jpg",
    resource:"즉석섭취식품[토마토/국산,시금치또띠아{밀가루(밀/미국산,호주산)},치킨커틀릿{닭고기(안심)/국산}],소스/말레이시아산,천연향신료[흑후추/베트남산]",
    kcal: 290,
    sodium: 950,
    sugars: 20,
    fat: 2.8,
    protein: 10,
  },
  {
    id: 12,
    title: "로스트치킨샐러드",
    content: "신선한 채소와 다양한 토핑으로 어우러진 영양",
    price: "8,500원",
    sort:"salad",
    image: "/salad.jpg",
    resource:"양상추/국산,로스트치킨브레스트[닭고기(가슴살/국산),정제소금/국산],발사믹오일드레싱[발사믹 비네거/프랑스산, 사양벌꿀/국산],방울토마토/국산",
    kcal: 120,
    sodium: 295,
    sugars: 5,
    fat: 1.3,
    protein: 6,
  },
  {
    id: 13,
    title: "로스팅호두파이",
    content: "로스팅 호두로 더욱 고소한 호두가 듬뿍",
    price: "36,000원",
    sort:"desert",
    image: "/hodupie.jpg",
    resource:"호두/미국산, 밀가루(밀/미국산), 버터/미국산",
    kcal: 395,
    sodium: 130,
    sugars: 25,
    fat: 8,
    protein: 6,
  },
  {
    id: 14,
    title: "뉴욕치즈타르트",
    content: "겉은 바삭한 쿠키에 진하고 묵직한 크림치즈 풍미를 듬뿍 담아 정성스레 구워낸 뉴욕치즈타르트",
    price: "3,200원",
    sort:"desert",
    image: "/cheesetart.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),설탕,자연치즈1/미국산(우유,크림,정제소금,로커스트콩검,치즈컬쳐),가공버터/뉴질랜드산,명가난황액(계란/국산)",
    kcal: 290,
    sodium: 220,
    sugars: 14,
    fat: 8,
    protein: 4,
  },
  {
    id: 15,
    title: "통밀치킨롤샌드위치",
    content: "칼로리는 낮지만 든든하게 꽉찬 포만감",
    price: "5,500원",
    sort:"salad",
    image: "/chickensandwich.jpg",
    resource:"빵류[밀가루(밀/미국산,캐나다산),설탕,스톤밀링통밀가루(밀/미국산),가공버터/뉴질랜드산,전란액],프레스햄[닭고기/국산,혼합제제1{정제소금,설탕,분말마늘,분말양파,분말생강,폴리인산나트륨,메타인산나트륨,피로인산나트륨,덱스트린,L-글루탐산나트륨(향미증진제),에리토브산나트륨(산화방지제),아질산나트륨(발색제)},소스{혼합간장(탈지대두/외국산)},두류가공품,글리신],토마토/국산,절임식품ⓛ[염장오이,기타과당,발효식초(주정,발효영양원)]",
    kcal: 300,
    sodium: 790,
    sugars: 9,
    fat: 2,
    protein: 11,
  },
];

export default data2;
