let data4 = [
  {
    id: 32,
    title: "슈크림빵",
    content: "폭신한 빵 속에 달콤하고 부드러운 노란빛의 슈크림이 가득!",
    price: "2,600원",
    sort:"bread",
    image: "/creambread.png",
    resource:"빵류[밀가루①(밀/캐나다산,미국산),우유(원유/국산)], 기타가공품/벨기에산",
    kcal: 230,
    sodium: 180,
    sugars: 14,
    fat: 3.3,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 33,
    title: "크로아상",
    content: "겹겹이 쌓인 결 사이로 진한 버터 풍미가 베어든 크로아상",
    price: "2,500원",
    sort:"bread",
    image: "/croissant.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),설탕,가공버터/프랑스산,명가난황액(계란/국산)",
    kcal: 480,
    sodium: 440,
    sugars: 10,
    fat: 18,
    protein: 8,
    allergy:"밀, 계란, 우유",
  },
  {
    id: 34,
    title: "갈릭크림치즈빵",
    content: "속살에 촉촉하게 밴 크림치즈와 갈릭소스의 중독성 있는 단짠맛",
    price: "3,600원",
    sort:"bread",
    image: "/garliccreambread.jpg",
    resource:"빵류[밀가루(밀/캐나다산,미국산),마가린/싱가포르산],기타가공품①[버터/미국산,마가린{가공유지 (팜에스테르화유/말레이시아산)},다진마늘(마늘/국산)],기타가공품②[크림치즈/호주산,마요네즈{채종유(채종유/호주산)}]",
    kcal: 520,
    sodium: 485,
    sugars: 11,
    fat: 13,
    protein: 8,
    allergy:"밀, 계란, 우유",
  },
  {
    id: 35,
    title: "소보루빵",
    content: "풍미깊은 크림치즈와 고소한데다가 입안 톡톡 터지는 옥수수와의 조화",
    price: "2,000원",
    sort:"bread",
    image: "/soboru.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),가공버터/뉴질랜드산,명가난황액(계란/국산)",
    kcal: 340,
    sodium: 230,
    sugars: 17,
    fat: 7,
    protein: 8,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 36,
    title: "단팥크림빵",
    content: "부드럽고 달콤한 통팥앙금과 크림의 만남",
    price: "2,200원",
    sort:"bread",
    image: "/traditionalbread.png",
    resource:"통팥앙금/중국산(팥,설탕,말티톨시럽,트레할로스,정제소금), 밀가루(밀/캐나다산,미국산), 버터/미국산, 설탕, 전란액, 쇼트닝, 기타설탕, 마가린①, 마가린②, 유크림, 마가린③, 화이트초콜릿, 식용유지가공품, 효모, 재제소금, 채종유, 이형제, 식물성이형유, 기타가공품, 천일염, 곡류가공품, 알긴산프로필렌글리콜, 혼합제제식품첨가물(합성향료,글리세린, 아라비아검, 정제수, 덱스트린, 정제가공유지, 주정, 트리아세틴)",
    kcal: 295,
    sodium: 230,
    sugars: 16,
    fat: 7,
    protein: 5,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 37,
    title: "갈릭고구마페스츄리",
    content: "겹겹이 바삭한 페스츄리에, 달콤한 고구마 앙금이 가득~ 게다가 마늘풍미까지!",
    price: "3,300원",
    sort:"bread",
    image: "/garlicsweetpotatopastry.jpg",
    resource:"밀가루/캐나다산,고구마/국산,과자[가공유크림/프랑스산,가공버터/뉴질랜드산,마늘/국산,난백액(계란/국산)]",
    kcal: 340,
    sodium: 390,
    sugars: 13,
    fat: 9,
    protein: 5,
    allergy:"밀, 계란, 대두, 우유",
  },
];

export default data4;
