let data3 = [
  {
    id: 24,
    title: "카스테라",
    content: "우리 벌꿀을 넣어 부드럽고 폭신폭신한 카스테라",
    price: "4,200원",
    sort:"bread",
    image: "/castella.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),설탕,자연치즈1/미국산(우유,크림,정제소금,로커스트콩검,치즈컬쳐),가공버터/뉴질랜드산,명가난황액(계란/국산)",
    kcal: 225,
    sodium: 80,
    sugars: 21,
    fat: 3,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 25,
    title: "쫀득쫀득 흑당호떡",
    content: "달콤한 흑당이 듬뿍~ 견과류로 더욱 고소하게",
    price: "2,200원",
    sort:"desert",
    image: "/hottuk.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),설탕,가공버터/프랑스산,명가난황액(계란/국산)",
    kcal: 410,
    sodium: 370,
    sugars: 25,
    fat: 4.5,
    protein: 7,
    allergy:"밀, 계란, 대두, 우유, 땅콩, 호두, 견과류",
  },
  {
    id: 26,
    title: "티라미수타르트",
    content: "진한 크림치즈와 아다지오 커피, 달콤한 가나슈가 어우러진 티라미수 타르트",
    price: "3,200원",
    sort:"desert",
    image: "/tiramisutart.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),가공버터/뉴질랜드산,계피분(계피/베트남산),명가난황액(계란/국산)",
    kcal: 390,
    sodium: 70,
    sugars: 16,
    fat: 16,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 27,
    title: "옥수수치즈타르트",
    content: "풍미깊은 크림치즈와 고소한데다가 입안 톡톡 터지는 옥수수와의 조화",
    price: "3,200원",
    sort:"desert",
    image: "/corntart.png",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),옥수수/국산,가공버터/뉴질랜드산,계피분(계피/베트남산),명가난황액(계란/국산)",
    kcal: 410,
    sodium: 75,
    sugars: 14,
    fat: 17,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유, 옥수수",
  },
  {
    id: 28,
    title: "초코퍼지쿠키",
    content: "퍼지의 쫄깃함과 단맛이 조화로운 쿠키",
    price: "2,000원",
    sort:"desert",
    image: "/chococookie.jpg",
    resource:"과자[가공유크림/프랑스산, 땅콩 또는 견과류가공품/미국산, 난백액(계란/국산)]",
    kcal: 390,
    sodium: 250,
    sugars: 30,
    fat: 7,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유, 땅콩, 견과류",
  },
  {
    id: 29,
    title: "크렌베리쿠키",
    content: "바삭하고 청키한 식감이 뛰어난 쿠키",
    price: "2,500원",
    sort:"desert",
    image: "/cranberrycookie.jpg",
    resource:"과자[가공유크림/프랑스산, 땅콩 또는 견과류가공품/미국산, 난백액(계란/국산)],인스피레이션 딸기초콜릿/프랑스산, 딸기분말(딸기/국산)]",
    kcal: 335,
    sodium: 330,
    sugars: 30,
    fat: 5,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유, 견과류",
  },
  {
    id: 30,
    title: "시나몬롤식빵",
    content: "향긋하고 달콤한 시나몬과 고소한 호두가 마블링 되어있는 시나몬롤식빵",
    price: "5,800원",
    sort:"bread",
    image: "/cinamonroll.jpg",
    resource:"빵류①[밀가루①(밀/캐나다산),밀가루②(밀/캐나다산,미국산),빵류②[밀가루(밀/미국산),땅콩분태/중국산],명가난황액(계란/국산),계피분(계피/베트남산)",
    kcal: 400,
    sodium: 330,
    sugars: 28,
    fat: 9,
    protein: 6,
    allergy:"밀, 계란, 대두, 우유, 땅콩, 호두",
  },
  {
    id: 31,
    title: "밤식빵",
    content: "풍성한 밤 알갱이로 묵직함을 선사하는 이 맛!",
    price: "6,000원",
    sort:"bread",
    image: "/chestnutbread.jpg",
    resource:"빵류①[밀가루①(밀/캐나다산),밀가루②(밀/캐나다산,미국산),조림류{밤다이스(당침밤(냉동밤다이스/중국산)),마론페이스트(체스트넛퓨레(밤퓨레/프랑스산))},밤페이스트p{밤페이스트(밤/국산)}], 땅콩또는견과류가공품(밤/중국산), 빵류②[밀가루(밀/미국산),땅콩분태/중국산]",
    kcal: 400,
    sodium: 350,
    sugars: 7,
    fat: 3,
    protein: 5.5,
    allergy:"밀, 계란, 대두, 우유, 밤, 땅콩, 견과류",
  },
];

export default data3;
