let data = [
  {
    id: 0,
    title: "샤인머스캣케이크",
    content: "알알이 톡톡! 상쾌하게 터지는 샤인머스캣 토핑과의 조합",
    price: "55,000원",
    sort:"cake",
    image: "/greencake.png",
    resource:"빵류[빵류{전란액(계란/국산)}, 식물성크림(팜핵부분경화유/인도네시아산)], 샤인머스캣/국산",
    kcal: 300,
    sodium: 90,
    sugars: 17,
    fat: 10,
    protein: 4,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 1,
    title: "유기농야채고로케",
    content: "향긋한 부추와 버섯까지! 게다가 바삭바삭함은 덤",
    price: "2,600원",
    sort:"bread",
    image: "/koroke.jpg",
    resource:"빵류[밀가루(밀/캐나다산,미국산),돈후지(돼지고기/국내산)], 해바라기유[고올레산해바라기유/외국산(스페인,아르헨티나,프랑스 등)], 곡류가공품(옥수수/이탈리아산,정제소금/이탈리아산)",
    kcal: 325,
    sodium: 550,
    sugars: 9,
    fat: 3.6,
    protein: 7,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 2,
    title: "꽈배기도넛",
    content: "쫄깃,촉촉,부드러움. 삼박자를 다 갖춘 풍성한 식감",
    price: "2,500원",
    sort:"bread",
    image: "/kwabegi.jpg",
    resource:"빵류[밀가루①(밀/캐나다산,미국산),밀가루②(밀/캐나다산,미국산)], 해바라기유[고올레산해바라기유/외국산(스페인,아르헨티나,프랑스 등)], 계피분(계피/베트남산)",
    kcal: 255,
    sodium: 260,
    sugars: 9,
    fat: 2.6,
    protein: 4,
    allergy:"밀, 대두, 우유",
  },
  {
    id: 3,
    title: "모닝토스트",
    content: "입속에 퍼지는 부드럽고 진한 풍미",
    price: "5,800원",
    sort:"bread",
    image: "/morningtoast.jpg",
    resource:"빵류[밀가루①(밀/미국산,캐나다산), 마가린(팜유/말레이시아산)], 기타가공품/벨기에산",
    kcal: 385,
    sodium: 460,
    sugars: 7,
    fat: 9,
    protein: 8,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 4,
    title: "치즈소세지페스츄리",
    content: "치즈와 소세지와 페스츄리가 만난 앙상블",
    price: "3,000원",
    sort:"bread",
    image: "/cheesesausagepastry.png",
    resource:"소시지(돼지고기/국산,돼지지방/국산,정제소금/국산), 빵류[밀가루①(밀/캐나다산,미국산),마가린(팜유/말레이시아산)], 가공치즈(자연치즈/뉴질랜드산,식물성유지/말레이시아산)",
    kcal: 390,
    sodium: 670,
    sugars: 3,
    fat: 11,
    protein: 12,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 5,
    title: "모카커피번",
    content: "중독성있는 겉바속촉과 단짠단짠",
    price: "3,000원",
    sort:"bread",
    image: "/coffeebon.png",
    resource:"빵류[밀가루(밀/캐나다산),알가공품(전란액/국내산)], 기타가공품[마가린{가공유지(팜에스테르화유/말레이시아산)},밀가루(밀/미국산),익스트랙트디카페/프랑스산,커피{커피/콜롬비아산57.96%,커피/브라질산32.04%,커피10%(커피원두/콜롬비아산35%,브라질산33%)}]",
    kcal: 405,
    sodium: 340,
    sugars: 13,
    fat: 14,
    protein: 6,
    allergy:"밀, 계란, 대두, 견과류",
  },
  {
    id: 6,
    title: "소세지피자빵",
    content: "대한민국을 대표하는 근본빵!",
    price: "3,200원",
    sort:"bread",
    image: "/sausagepizza.jpg",
    resource:"빵류[밀가루(밀/미국산,캐나다산),쇼트닝(팜올레인유/말레이시아산)], 소시지(돼지고기/국산,돼지지방/국산,정제소금/국산), 기타가공품[마요네즈{콩기름(콩기름/외국산)},냉동혼합야채/중국산]",
    kcal: 340,
    sodium: 460,
    sugars: 9,
    fat: 5,
    protein: 7,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 7,
    title: "스마일케이크",
    content: "보고만 있어도 미소가 지어지는 사랑스러움",
    price: "41,000원",
    sort:"cake",
    image: "/smilecake.png",
    resource:"빵류[밀가루(밀/미국산),설탕,난백액(계란/국산),전란액,마가린],마가린[가공유지(팜에스테르화유/말레이시아산,팜핵에스테르화유/말레이시아산),식물성유지(대두유/외국산),기타과당,설탕,정제소금],설탕,오렌지마말레이드[설탕,오렌지/칠레산,레몬과즙농축액(레몬/이스라엘산),합성향료(오렌지오일향),소브산칼륨(보존료)],화이트초콜릿",
    kcal: 480,
    sodium: 160,
    sugars: 31,
    fat: 6,
    protein: 3,
    allergy:"밀, 계란, 우유, 땅콩, 호두, 복숭아, 오렌지, 동물유지",
  },
  {
    id: 8,
    title: "고구마반생크림반케이크",
    content: "달콤한 고구마케이크와 상큼한 딸기생크림케이크가 어우러진 반반케이크",
    price: "46,000원",
    sort:"cake",
    image: "/halfhalfcake.png",
    resource:"빵류[군고구마페이스트/인도네시아산,식물성크림(팜핵부분경화유/인도네시아산,정제소금/미국산),호박고구마다이스(호박고구마/국산)],샤인머스캣/국산",
    kcal: 220,
    sodium: 80,
    sugars: 10,
    fat: 6,
    protein: 3,
    allergy:"밀, 계란, 동물유지, 우유"
  },
  {
    id: 9,
    title: "뉴욕치즈케이크",
    content: "크림치즈 본연의 맛을 더해 부드럽고 촉촉한 치즈케이크",
    price: "37,000원",
    sort:"cake",
    image: "/cheesecake.png",
    resource:"자연치즈1/미국산(우유,크림,정제소금,로커스트콩검,치즈컬쳐),자연치즈2/호주산(우유,크림,정제소금,스테빌라이저,스타터컬쳐),설탕,빵류[설탕,밀가루(밀/미국산),난백액(계란/국산)",
    kcal: 325,
    sodium: 190,
    sugars: 25,
    fat: 12,
    protein: 7,
    allergy:"밀, 계란, 대두, 우유"
  },
  {
    id: 10,
    title: "블레싱 레드베리",
    content: "축복이라는 꽃말의 포인세티아를 모티브한 고급디자인",
    price: "39,000원",
    sort:"cake",
    image: "/redcake.png",
    resource:"빵류[빵류{전란액(계란/국산)},가공유크림/프랑스산, 냉동딸기①/칠레산, 냉동딸기②/폴란드산],딸기/국산",
    kcal: 195,
    sodium: 65,
    sugars: 12,
    fat: 4.3,
    protein: 3,
    allergy:"밀, 계란, 동물유지, 우유"
  },
  {
    id: 11,
    title: "치킨커틀릿샐러드랩",
    content: "다이어터를 위한 든든하고 건강한 한 끼로 강력추천!",
    price: "6,100원",
    sort:"salad",
    image: "/chickensalad.jpg",
    resource:"즉석섭취식품[토마토/국산,시금치또띠아{밀가루(밀/미국산,호주산)},치킨커틀릿{닭고기(안심)/국산}],소스/말레이시아산,천연향신료[흑후추/베트남산]",
    kcal: 290,
    sodium: 950,
    sugars: 20,
    fat: 2.8,
    protein: 10,
    allergy:"닭고기",
  },
  {
    id: 12,
    title: "로스트치킨샐러드",
    content: "신선한 채소와 다양한 토핑으로 어우러진 영양",
    price: "8,500원",
    sort:"salad",
    image: "/salad.jpg",
    resource:"양상추/국산,로스트치킨브레스트[닭고기(가슴살/국산),정제소금/국산],발사믹오일드레싱[발사믹 비네거/프랑스산, 사양벌꿀/국산],방울토마토/국산",
    kcal: 120,
    sodium: 295,
    sugars: 5,
    fat: 1.3,
    protein: 6,
    allergy:"닭고기",
  },
  {
    id: 13,
    title: "로스팅호두파이",
    content: "로스팅 호두로 더욱 고소한 호두가 듬뿍",
    price: "36,000원",
    sort:"desert",
    image: "/hodupie.jpg",
    resource:"호두/미국산, 밀가루(밀/미국산), 버터/미국산",
    kcal: 395,
    sodium: 130,
    sugars: 25,
    fat: 8,
    protein: 6,
    allergy:"밀, 계란, 대두, 호두, 땅콩, 견과류",
  },
  {
    id: 14,
    title: "뉴욕치즈타르트",
    content: "겉은 바삭한 쿠키에 진하고 묵직한 크림치즈 풍미를 듬뿍 담아 정성스레 구워낸 뉴욕치즈타르트",
    price: "3,200원",
    sort:"desert",
    image: "/cheesetart.jpg",
    resource:"우유/국산,밀가루(밀/미국산,캐나다산),설탕,자연치즈1/미국산(우유,크림,정제소금,로커스트콩검,치즈컬쳐),가공버터/뉴질랜드산,명가난황액(계란/국산)",
    kcal: 290,
    sodium: 220,
    sugars: 14,
    fat: 8,
    protein: 4,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 15,
    title: "통밀치킨롤샌드위치",
    content: "칼로리는 낮지만 든든하게 꽉찬 포만감",
    price: "5,500원",
    sort:"salad",
    image: "/chickensandwich.jpg",
    resource:"빵류[밀가루(밀/미국산,캐나다산),설탕,스톤밀링통밀가루(밀/미국산),가공버터/뉴질랜드산,전란액],프레스햄[닭고기/국산,혼합제제1{정제소금,설탕,분말마늘,분말양파,분말생강,폴리인산나트륨,메타인산나트륨,피로인산나트륨,덱스트린,L-글루탐산나트륨(향미증진제),에리토브산나트륨(산화방지제),아질산나트륨(발색제)},소스{혼합간장(탈지대두/외국산)},두류가공품,글리신],토마토/국산,절임식품ⓛ[염장오이,기타과당,발효식초(주정,발효영양원)]",
    kcal: 300,
    sodium: 790,
    sugars: 9,
    fat: 2,
    protein: 11,
    allergy:"밀, 닭고기",
  },
];

export default data;
