let data = [
  {
    id: 0,
    title: "샤인머스캣케이크",
    content: "알알이 톡톡 터지는 샤인머스캣 토핑과의 조합",
    price: "55,000원",
    sort:"cake",
    image: "/greencake.png",
  },
  {
    id: 1,
    title: "유기농야채고로케",
    content: "향긋한 부추와 버섯까지! 게다가 바삭바삭함은 덤",
    price: "2,600원",
    sort:"bread",
    image: "/koroke.jpg",
  },
  {
    id: 2,
    title: "꽈배기도넛",
    content: "쫄깃,촉촉,부드러움. 삼박자를 다 갖춘 풍성한 식감",
    price: "2,500원",
    sort:"bread",
    image: "/kwabegi.jpg",
  },
  {
    id: 3,
    title: "모닝토스트",
    content: "입속에 퍼지는 부드럽고 진한 풍미",
    price: "5,800원",
    sort:"bread",
    image: "/morningtoast.jpg",
  },
  {
    id: 4,
    title: "치즈소세지페스츄리",
    content: "치즈와 소세지와 페스츄리가 만난 앙상블",
    price: "3,000원",
    sort:"bread",
    image: "/cheesesausagepastry.png",
  },
  {
    id: 5,
    title: "모카커피번",
    content: "중독성있는 겉바속촉과 단짠단짠",
    price: "3,000원",
    sort:"bread",
    image: "/coffeebon.png",
  },
  {
    id: 6,
    title: "소세지피자빵",
    content: "대한민국을 대표하는 근본빵!",
    price: "3,200원",
    sort:"bread",
    image: "/sausagepizza.jpg",
  },
  {
    id: 7,
    title: "스마일케이크",
    content: "보고만 있어도 미소가 지어지는 사랑스러움",
    price: "41,000원",
    sort:"cake",
    image: "/smilecake.png",
  },
];

export default data;
