let data2 = [
  {
    id: 16,
    title: "스파이시미트칠리핫도그",
    content: "육즙가득한 소시지와 매콤한 칠리소스가 입안 가득!",
    price: "4,000원",
    sort:"bread",
    image: "/chilliehotdog.jpg",
    resource:"즉석조리식품[소시지(돼지고기/국산, 돼지지방/국산), 빵류{밀가루(밀/미국산, 캐나다산)}, 기타가공품{고춧가루(고추/국산)}, 크러쉬드레드페퍼/인도산], 마요네즈[채종유(채종유/호주산), 난황액(난황액/국산)], 파슬리후레이크/네덜란드산",
    kcal: 320,
    sodium: 590,
    sugars: 4,
    fat: 7,
    protein: 13,
    allergy:"닭고기",
  },
  {
    id: 17,
    title: "초코칩꽈배기",
    content: "맛있는 바삭함, 기분좋은 달콤함",
    price: "3,000원",
    sort:"bread",
    image: "/chocochiptwist.jpg",
    resource:"빵류[밀가루①(밀/캐나다산,미국산),우유/국내산], 기타가공품/벨기에산",
    kcal: 585,
    sodium: 320,
    sugars: 20,
    fat: 7,
    protein: 7,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 18,
    title: "옥수수소보루크림빵",
    content: "달콤고소한 소보루빵에 옥수수와 크림이 만났다",
    price: "2,700원",
    sort:"bread",
    image: "/cornsoboru.jpg",
    resource:"빵류[빵류{전란액(계란/국산)},가공유크림/프랑스산,기타가공품/벨기에산,옥수수/국산",
    kcal: 365,
    sodium: 190,
    sugars: 27,
    fat: 5,
    protein: 2,
    allergy:"밀, 계란, 동물유지, 우유, 옥수수",
  },
  {
    id: 19,
    title: "찹쌀도넛",
    content: "쫀득쫀득한 식감이 너도나도 기분좋아지는 맛",
    price: "1,800원",
    sort:"bread",
    image: "/minidonut.jpg",
    resource:"빙수용통단팥[팥/중국산, 정제소금/국산], 단팥소[팥 /중국산, 정제소금/국산], 찹쌀가루(찹쌀/국산),밀가루(밀/미국산), 마가린[식물성유지(대두유/외국산),가공유지(팜스테아린에스테르화유/말레이시아산, 채종경화에스테르화유)]",
    kcal: 315,
    sodium: 240,
    sugars: 17,
    fat: 1.4,
    protein: 5,
    allergy:"밀, 대두, 견과류",
  },
  {
    id: 20,
    title: "리코타치킨샐러드",
    content: "부드러운 리코타치즈와 신선한 채소, 입맛을 돋구는 발사믹드레싱",
    price: "7,000원",
    sort:"salad",
    image: "/ricotasalad.jpg",
    resource:"양상추/국산,로스트치킨브레스트[닭고기(가슴살/국산),정제소금/국산],유제품/네덜란드산,발사믹오일드레싱[발사믹 비네거/프랑스산, 사양벌꿀/국산],방울토마토/국산",
    kcal: 200,
    sodium: 200,
    sugars: 14,
    fat: 4,
    protein: 7,
    allergy:"계란, 닭고기",
  },
  {
    id: 21,
    title: "순우유케이크",
    content: "로스팅 호두로 더욱 고소한 호두가 듬뿍",
    price: "40,000원",
    sort:"cake",
    image: "/milkcake.jpg",
    resource:"빵류[설탕, 난백액(계란/국산), 전란액(계란/국산), 밀가루, 채종유],마가린[가공유지(팜에스테르화유/말레이시아산, 팜핵에스테르화유/말레이시아산), 식물성유지(대두유/외국산), 기타과당, 설탕, 정제소금], 화이트초콜릿①{화이트초콜릿①/이탈리아산,치자황색소,혼합제제[대두유, 글리세린지방산에스테르,정제수",
    kcal: 315,
    sodium: 90,
    sugars: 11,
    fat: 14,
    protein: 4,
    allergy:"밀, 계란, 동물유지, 우유",
  },
  {
    id: 22,
    title: "우유크림슈",
    content: "달달함에 더해 몽글몽글 기분까지 좋아지는 식감!",
    price: "2,900원",
    sort:"desert",
    image: "/shewcream.jpg",
    resource:"가공유크림[가공유크림/독일산, 유크림(유크림/국산), 우유/국산] , 빵류[계란/국산, 마가린/싱가포르산]",
    kcal: 350,
    sodium: 140,
    sugars: 21,
    fat: 15,
    protein: 7,
    allergy:"밀, 계란, 동물유지, 우유",
  },
  {
    id: 23,
    title: "갈릭브레드",
    content: "빵 사이사이 달콤꾸덕 갈릭소스가 듬뿍",
    price: "5,800원",
    sort:"bread",
    image: "/garlicbread.jpg",
    resource:"빵류[밀가루①(밀/캐나다산),밀가루②(밀/캐나다산,미국산),건마늘(분말){건마늘(마늘/중국산)},다진마늘(마늘/국내산)], 버터갈릭소스P[마요네즈{콩기름(콩기름/외국산)},다진마늘(마늘/국산)], 우유(원유/국산)",
    kcal: 450,
    sodium: 470,
    sugars: 20,
    fat: 5,
    protein: 6,
    allergy:"밀, 계란, 대두, 동물유지, 우유",
  },
];

export default data2;
