let data = [
  {
    id: 0,
    title: "샤인머스캣케이크",
    content: "알알이 톡톡! 상쾌하게 터지는 샤인머스캣 토핑과의 조합",
    price: "55,000원",
    sort:"cake",
    image: "/greencake.png",
    resource:"빵류[빵류{전란액(계란/국산)}, 식물성크림(팜핵부분경화유/인도네시아산)], 샤인머스캣/국산",
    kcal: 300,
    sodium: 90,
    sugars: 17,
    fat: 10,
    protein: 4,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 1,
    title: "유기농야채고로케",
    content: "향긋한 부추와 버섯까지! 게다가 바삭바삭함은 덤",
    price: "2,600원",
    sort:"bread",
    image: "/koroke.jpg",
    resource:"빵류[밀가루(밀/캐나다산,미국산),돈후지(돼지고기/국내산)], 해바라기유[고올레산해바라기유/외국산(스페인,아르헨티나,프랑스 등)], 곡류가공품(옥수수/이탈리아산,정제소금/이탈리아산)",
    kcal: 325,
    sodium: 550,
    sugars: 9,
    fat: 3.6,
    protein: 7,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 2,
    title: "꽈배기도넛",
    content: "쫄깃,촉촉,부드러움. 삼박자를 다 갖춘 풍성한 식감",
    price: "2,500원",
    sort:"bread",
    image: "/kwabegi.jpg",
    resource:"빵류[밀가루①(밀/캐나다산,미국산),밀가루②(밀/캐나다산,미국산)], 해바라기유[고올레산해바라기유/외국산(스페인,아르헨티나,프랑스 등)], 계피분(계피/베트남산)",
    kcal: 255,
    sodium: 260,
    sugars: 9,
    fat: 2.6,
    protein: 4,
    allergy:"밀, 대두, 우유",
  },
  {
    id: 3,
    title: "모닝토스트",
    content: "입속에 퍼지는 부드럽고 진한 풍미",
    price: "5,800원",
    sort:"bread",
    image: "/morningtoast.jpg",
    resource:"빵류[밀가루①(밀/미국산,캐나다산), 마가린(팜유/말레이시아산)], 기타가공품/벨기에산",
    kcal: 385,
    sodium: 460,
    sugars: 7,
    fat: 9,
    protein: 8,
    allergy:"밀, 계란, 대두, 우유",
  },
  {
    id: 4,
    title: "치즈소세지페스츄리",
    content: "치즈와 소세지와 페스츄리가 만난 앙상블",
    price: "3,000원",
    sort:"bread",
    image: "/cheesesausagepastry.png",
    resource:"소시지(돼지고기/국산,돼지지방/국산,정제소금/국산), 빵류[밀가루①(밀/캐나다산,미국산),마가린(팜유/말레이시아산)], 가공치즈(자연치즈/뉴질랜드산,식물성유지/말레이시아산)",
    kcal: 390,
    sodium: 670,
    sugars: 3,
    fat: 11,
    protein: 12,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 5,
    title: "모카커피번",
    content: "중독성있는 겉바속촉과 단짠단짠",
    price: "3,000원",
    sort:"bread",
    image: "/coffeebon.png",
    resource:"빵류[밀가루(밀/캐나다산),알가공품(전란액/국내산)], 기타가공품[마가린{가공유지(팜에스테르화유/말레이시아산)},밀가루(밀/미국산),익스트랙트디카페/프랑스산,커피{커피/콜롬비아산57.96%,커피/브라질산32.04%,커피10%(커피원두/콜롬비아산35%,브라질산33%)}]",
    kcal: 405,
    sodium: 340,
    sugars: 13,
    fat: 14,
    protein: 6,
    allergy:"밀, 계란, 대두, 견과류",
  },
  {
    id: 6,
    title: "소세지피자빵",
    content: "대한민국을 대표하는 근본빵!",
    price: "3,200원",
    sort:"bread",
    image: "/sausagepizza.jpg",
    resource:"빵류[밀가루(밀/미국산,캐나다산),쇼트닝(팜올레인유/말레이시아산)], 소시지(돼지고기/국산,돼지지방/국산,정제소금/국산), 기타가공품[마요네즈{콩기름(콩기름/외국산)},냉동혼합야채/중국산]",
    kcal: 340,
    sodium: 460,
    sugars: 9,
    fat: 5,
    protein: 7,
    allergy:"밀, 계란, 돼지고기",
  },
  {
    id: 7,
    title: "스마일케이크",
    content: "보고만 있어도 미소가 지어지는 사랑스러움",
    price: "41,000원",
    sort:"cake",
    image: "/smilecake.png",
    resource:"빵류[밀가루(밀/미국산),설탕,난백액(계란/국산),전란액,마가린],마가린[가공유지(팜에스테르화유/말레이시아산,팜핵에스테르화유/말레이시아산),식물성유지(대두유/외국산),기타과당,설탕,정제소금],설탕,오렌지마말레이드[설탕,오렌지/칠레산,레몬과즙농축액(레몬/이스라엘산),합성향료(오렌지오일향),소브산칼륨(보존료)],화이트초콜릿",
    kcal: 480,
    sodium: 160,
    sugars: 31,
    fat: 6,
    protein: 3,
    allergy:"밀, 계란, 우유, 땅콩, 호두, 복숭아, 오렌지, 동물유지",
  },
];

export default data;
